[build]
default-target = "arm-unknown-linux-gnueabihf"

[target.arm-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes libasound2-dev:armhf --no-install-recommends",
]
