[build]
default-target = "arm-unknown-linux-gnueabi"

[target.arm-unknown-linux-gnueabi]
pre-build = [
    "dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes libasound2-dev:armhf",
]
